# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStructure',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(default='app/static/img/data-structure-img/no-img.jpg', upload_to='app/static/img/data_structure_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('nodeId', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('prev', models.CharField(blank=True, max_length=64, null=True)),
                ('next', models.CharField(blank=True, max_length=64, null=True)),
                ('fanout', models.CharField(blank=True, max_length=64, null=True)),
                ('fanoutFixedValue', models.IntegerField(blank=True, null=True)),
                ('fanoutFunction', models.CharField(blank=True, max_length=64, null=True)),
                ('partitioning', models.CharField(blank=True, max_length=64, null=True)),
                ('partitioningFunction', models.CharField(blank=True, max_length=64, null=True)),
                ('filtersPerLevel', models.CharField(blank=True, max_length=64, null=True)),
                ('filtersPerRun', models.CharField(blank=True, max_length=64, null=True)),
                ('initialRunSize', models.IntegerField(blank=True, null=True)),
                ('maxRunsPerLevel', models.IntegerField(blank=True, null=True)),
                ('mergeFactor', models.IntegerField(blank=True, null=True)),
                ('sorted', models.CharField(blank=True, max_length=64, null=True)),
                ('directAddressing', models.CharField(blank=True, max_length=64, null=True)),
                ('head', models.CharField(blank=True, max_length=64, null=True)),
                ('tail', models.CharField(blank=True, max_length=64, null=True)),
                ('prevLinks', models.CharField(blank=True, max_length=64, null=True)),
                ('nextLinks', models.CharField(blank=True, max_length=64, null=True)),
                ('skiplinks', models.CharField(blank=True, max_length=64, null=True)),
                ('skiplinksProbability', models.IntegerField(blank=True, null=True)),
                ('zoneMapMax', models.CharField(blank=True, max_length=64, null=True)),
                ('zoneMapMin', models.CharField(blank=True, max_length=64, null=True)),
                ('bloomFilters', models.CharField(blank=True, max_length=64, null=True)),
                ('HashFunctionsNum', models.IntegerField(blank=True, null=True)),
                ('NumOfBits', models.IntegerField(blank=True, null=True)),
                ('keyRetention', models.CharField(blank=True, max_length=64, null=True)),
                ('keyRetentionCompression', models.CharField(blank=True, max_length=64, null=True)),
                ('keyRetentionFunction', models.CharField(blank=True, max_length=64, null=True)),
                ('valueRetention', models.CharField(blank=True, max_length=64, null=True)),
                ('valueRetentionCompression', models.CharField(blank=True, max_length=64, null=True)),
                ('valueRetentionFunction', models.CharField(blank=True, max_length=64, null=True)),
                ('capacity', models.CharField(blank=True, max_length=64, null=True)),
                ('capacityValue', models.IntegerField(blank=True, null=True)),
                ('capacityFunction', models.CharField(blank=True, max_length=64, null=True)),
                ('Utilization', models.CharField(blank=True, max_length=64, null=True)),
                ('UtilizationFunction', models.CharField(blank=True, max_length=64, null=True)),
                ('linksLayout', models.CharField(blank=True, max_length=64, null=True)),
                ('filtersLayout', models.CharField(blank=True, max_length=64, null=True)),
                ('keyValueLayout', models.CharField(blank=True, max_length=64, null=True)),
                ('accessPartitions', models.CharField(blank=True, max_length=64, null=True)),
                ('color', models.CharField(max_length=64, null=True)),
                ('shortName', models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
